### ISSUE TITLE
다시 빌드한 xformers 0.0.15버전

### ISSUE THREAD

**Issue by Bing-su** [toriato/easy-stable-diffusion#2]
요즘 챈에 xformers 안된다는 글이 자주 보여서
코랩에서 빌드해봤어요

저는 이걸로 설치하니까 되네요

https://huggingface.co/Bingsu/my_checkpoints/resolve/main/xformers-0.0.15.dev0%2Baffe4da.d20221211-cp38-cp38-linux_x86_64.whl

**Comment by toriato** [comment]
👍

제가 이전에 컴파일한 커밋에선 SAI 레포지토리에서 xformers 구동에 필요한 부분이 빠져있었던거 같아요
웹UI에서 사용하는 SD 레포지토리 교체한 이후로 계속 오류 발생하는거 같은데...
컴파일 다시 굴리긴 귀찮으니까 일단 올려주신 주소로 교체만 해둘게요
감사합니다!!!
